# Generated by Django 4.1.9 on 2023-08-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='notification_status',
            field=models.BooleanField(null=True),
        ),
    ]
