# Generated by Django 4.1.9 on 2023-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_searchmodel_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='book_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
