# Generated by Django 4.1.9 on 2023-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_searchmodel_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
    ]
