 # Generated by Django 4.1.9 on 2023-06-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='added_date',
            field=models.DateField(default='2023-12-13'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='latitude',
            field=models.FloatField(default=28.26689),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='longitude',
            field=models.FloatField(default=83.96851),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(upload_to='books/images'),
        ),
    ]
