# Generated by Django 4.1.9 on 2023-08-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmodel',
            name='notification_status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
