# Generated by Django 4.1.9 on 2023-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_bookinfo_added_date_bookinfo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='category',
            field=models.CharField(choices=[('+2', '+2'), ('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Noovels & More', 'Novels & More'), ('School', 'School')], max_length=100),
        ),
    ]
