# Generated by Django 4.1.9 on 2023-09-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_bookedmodel_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='location',
            field=models.CharField(default='Gharmi, Pokhara-16, Pokhara, Kaski', max_length=200),
        ),
    ]
