# Generated by Django 4.1.9 on 2023-06-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_alter_bookinfo_image'),
        ('bookinfo', '0003_alter_bookinfo_category'),
    ]

    operations = [
    ]
