# Generated by Django 4.1.9 on 2023-10-02 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookinfo', '0003_bookinfo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldbookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('postedduration', models.IntegerField()),
                ('sellingprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyername', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
