# Generated by Django 4.2.1 on 2023-08-06 05:47
# Generated by Django 4.1.9 on 2023-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0005_cateogory_alter_bookinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='added_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
