# Generated by Django 4.1.9 on 2023-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_userinfomodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='Profile_photo',
            field=models.ImageField(null=True, upload_to='user/images'),
        ),
    ]
